services:

    tianos.listener.doctrine.session:
        class: Bundle\SessionBundle\EventListener\DoctrineListenerService
        arguments: ["@security.token_storage"]
        tags:
          - { name: doctrine.event_listener, event: postUpdate }
          - { name: doctrine.event_listener, event: preUpdate }
          - { name: doctrine.event_listener, event: prePersist }
          - { name: doctrine.event_listener, event: postLoad }
          - { name: doctrine.event_listener, event: postRemove }

    tianos.api.controller.session:
        class: Bundle\SessionBundle\Controller\ApiController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.api.controller.session, alias: tianos.api.controller.session }

    tianos.backend.controller.session:
        class: Bundle\SessionBundle\Controller\BackendController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.backend.controller.session, alias: tianos.backend.controller.session }

    tianos.frontend.controller.session:
        class: Bundle\SessionBundle\Controller\FrontendController
        arguments: [ Bundle\ResourceBundle\Factory\RequestConfigurationFactoryInterface ]
        tags:
            - { name: tianos.frontend.controller.session, alias: tianos.frontend.controller.session }

    tianos.repository.session:
        class: Dummy
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [ Bundle\SessionBundle\Entity\Session ]



#    tianos.controller.grid:
#        class: Bundle\GridBundle\Controller\GridController
#        arguments: [ Bundle\GridBundle\Controller\RequestConfigurationFactoryInterface ]
#        tags:
#            - { name: tianos.controller.grid, alias: tianos.controller.grid }